// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2R1lMRxlKfIvqVgiHlKjNQGYEx0EjYJk',
    appId: '1:438563238214:web:018c5db497cda233267547',
    messagingSenderId: '438563238214',
    projectId: 'boneapp-41f36',
    authDomain: 'boneapp-41f36.firebaseapp.com',
    storageBucket: 'boneapp-41f36.appspot.com',
    measurementId: 'G-SBQRKQK0LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsZSK1DtGYgEWGxyYPyFuHfkuEiLFCeEU',
    appId: '1:438563238214:android:d04c5c75475fc7b7267547',
    messagingSenderId: '438563238214',
    projectId: 'boneapp-41f36',
    storageBucket: 'boneapp-41f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltLEgqSTBbcY1vsoCKKCxcN_dzIGk5U0',
    appId: '1:438563238214:ios:1157bec4418c5f55267547',
    messagingSenderId: '438563238214',
    projectId: 'boneapp-41f36',
    storageBucket: 'boneapp-41f36.appspot.com',
    iosBundleId: 'com.example.boneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltLEgqSTBbcY1vsoCKKCxcN_dzIGk5U0',
    appId: '1:438563238214:ios:6caa69fb126e32f6267547',
    messagingSenderId: '438563238214',
    projectId: 'boneapp-41f36',
    storageBucket: 'boneapp-41f36.appspot.com',
    iosBundleId: 'com.example.boneApp.RunnerTests',
  );
}
