name: bone_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  firebase_core: ^3.2.0 
  google_sign_in: ^6.2.1 
  firebase_auth: ^5.1.4
  sign_in_button: ^3.0.0
  shared_preferences: ^2.3.2 
  image_picker: ^0.8.9
  tflite_flutter: ^0.11.0
  image: ^3.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Logo.png
    - lib/assets/Google.png
    - lib/assets/logoHorizontal.png
    - lib/assets/Xray.png
    - lib/assets/Xray2.png
    - lib/assets/Xray3.png
    - lib/assets/ProfilePic.png
    - lib/assets/BG Image.png
    - lib/assets/Onboarding1.png
    - lib/assets/Onboarding2.png
    - lib/assets/Onboarding3.png
    - assets/kneeosteoarthritis_model.tflite
    - assets/labels.txt
